// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/widget/TtButton/src/button.vue')['default']
    Calendar: typeof import('./src/components/widget/TtCalendar/src/calendar.vue')['default']
    Checkbox: typeof import('./src/components/widget/TtCheckbox/src/checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/components/widget/TtCheckbox/src/checkboxGroup.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    EChartsComponents: typeof import('./src/components/Echarts/EChartsComponents.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Icon: typeof import('./src/components/widget/TtIcon/src/icon.vue')['default']
    Input: typeof import('./src/components/widget/TtInput/src/input.vue')['default']
    LeetCodeHeader: typeof import('./src/components/LeetCodeHeader.vue')['default']
    LeetCodeNav: typeof import('./src/components/LeetCodeNav.vue')['default']
    LeetCodeTemplate: typeof import('./src/components/LeetCodeTemplate.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Popper: typeof import('./src/components/widget/TtPopper/src/popper.vue')['default']
    Radio: typeof import('./src/components/widget/TtRadio/src/radio.vue')['default']
    RadioGroup: typeof import('./src/components/widget/TtRadio/src/radioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/widget/TtSelect/src/select.vue')['default']
    SelectContent: typeof import('./src/components/widget/TtSelect/src/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/widget/TtSelect/src/selectGroup.vue')['default']
    SelectItem: typeof import('./src/components/widget/TtSelect/components/SelectItem.vue')['default']
    Src: typeof import('./src/components/widget/TtSelect/src/index.vue')['default']
    Tooltip: typeof import('./src/components/widget/TtToolTip/src/tooltip.vue')['default']
    Trigger: typeof import('./src/components/widget/TtPopper/src/trigger.vue')['default']
    TtSelect: typeof import('./src/components/widget/TtSelect/index.vue')['default']
    TtToolTip: typeof import('./src/components/widget/TtToolTip/index.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList.vue')['default']
  }
}

export {}
